framework:
    messenger:
        default_bus: message.bus

        buses:
            message.bus:
            event.bus:
                default_middleware: allow_no_handlers

        transports:
            async:
                dsn: '%env(resolve:MESSENGER_ASYNC_EVENTS_DSN)%'
                retry_strategy:
                    max_retries: 0

        routing:
            Application\Event\ApplicationEvent: async
            Domain\Loan\Event\DomainEvent: async
